openapi: 3.0.0
info:
  title: API de Verificación de Rostros y Usuarios
  description: API para la verificación de rostros, inicio de sesión y registro de usuarios.
  version: 1.0.1
servers:
  - url: http://localhost:5000
    description: Servidor local
  - url: https://living-improved-ocelot.ngrok-free.app/
    description: Servidor en linea

paths:
  /api/student-signup:
    post:
      summary: Registrar estudiante
      description: Registra un nuevo estudiante proporcionando los datos necesarios.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Nombre completo del estudiante.
                username:
                  type: string
                  description: Nombre de usuario.
                age:
                  type: integer
                  description: Edad del estudiante.
                faculty:
                  type: string
                  description: Facultad a la que pertenece el estudiante.
                matnum:
                  type: string
                  description: Número de matrícula.
                password:
                  type: string
                  description: Contraseña del estudiante.
                face_img:
                  type: string
                  format: base64
                  description: Imagen de rostro en base64.
                email:
                  type: string
                  format: email
                  description: Correo electrónico del estudiante.
              required:
                - name
                - username
                - age
                - faculty
                - matnum
                - password
                - face_img
                - email
      responses:
        '201':
          description: Registro de estudiante exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      message:
                        type: string
                  status_code:
                    type: integer
        '400':
          description: Faltan campos en la solicitud
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
                  status_code:
                    type: integer
        '409':
          description: Estudiante ya registrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
                  status_code:
                    type: integer
                  duplicate_field:
                    type: string
                    description: Campo que causa la violación de unicidad (username, matnum o email).
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
                  status_code:
                    type: integer

  /api/student-login:
    post:
      summary: Iniciar sesión de estudiante
      description: Permite a un estudiante iniciar sesión proporcionando su número de matrícula y contraseña.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                matnum:
                  type: string
                  description: Número de matrícula del estudiante.
                password:
                  type: string
                  description: Contraseña del estudiante.
              required:
                - matnum
                - password
      responses:
        '200':
          description: Inicio de sesión exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      message:
                        type: string
                      face_img:
                        type: string
                        format: base64
                        description: Imagen de rostro en base64.
                  status_code:
                    type: integer
        '400':
          description: Solicitud incorrecta, campos faltantes
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
                  status_code:
                    type: integer
        '402':
          description: Estudiante no encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
                  status_code:
                    type: integer
        '403':
          description: Contraseña incorrecta
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
                  status_code:
                    type: integer
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
                  status_code:
                    type: integer

  /api/teacher-signup:
    post:
      summary: Registrar profesor
      description: Registra un nuevo profesor proporcionando los datos necesarios.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Nombre completo del profesor.
                username:
                  type: string
                  description: Nombre de usuario.
                age:
                  type: integer
                  description: Edad del profesor.
                faculty:
                  type: string
                  description: Facultad a la que pertenece el profesor.
                worknum:
                  type: string
                  description: Número de trabajo.
                password:
                  type: string
                  description: Contraseña del profesor.
                face_img:
                  type: string
                  format: base64
                  description: Imagen de rostro en base64.
                email:
                  type: string
                  format: email
                  description: Correo electrónico del profesor.
              required:
                - name
                - username
                - age
                - faculty
                - worknum
                - password
                - face_img
                - email
      responses:
        '201':
          description: Registro de profesor exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      message:
                        type: string
                  status_code:
                    type: integer
        '400':
          description: Faltan campos en la solicitud
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
                  status_code:
                    type: integer
        '409':
          description: Profesor ya registrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
                  status_code:
                    type: integer
                  duplicate_field:
                    type: string
                    description: Campo que causa la violación de unicidad (username, worknum o email).
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
                  status_code:
                    type: integer

  /api/teacher-login:
    post:
      summary: Iniciar sesión de profesor
      description: Permite a un profesor iniciar sesión proporcionando su número de trabajo y contraseña.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                worknum:
                  type: string
                  description: Número de trabajo del profesor.
                password:
                  type: string
                  description: Contraseña del profesor.
              required:
                - worknum
                - password
      responses:
        '200':
          description: Inicio de sesión exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      message:
                        type: string
                      face_img:
                        type: string
                        format: base64
                        description: Imagen de rostro en base64.
                  status_code:
                    type: integer
        '400':
          description: Solicitud incorrecta, campos faltantes
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
                  status_code:
                    type: integer
        '402':
          description: Profesor no encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
                  status_code:
                    type: integer
        '403':
          description: Contraseña incorrecta
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
                  status_code:
                    type: integer
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
                  status_code:
                    type: integer

  /api/verify-face:
    post:
      summary: Verificar coincidencia de rostros
      description: Compara dos imágenes de rostros y determina si coinciden.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cap_frame:
                  type: string
                  format: base64
                  description: Imagen capturada en formato base64.
                ref_frame:
                  type: string
                  format: base64
                  description: Imagen de referencia en formato base64.
              required:
                - cap_frame
                - ref_frame
      responses:
        '200':
          description: Coincidencia de rostros exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      match:
                        type: boolean
                  status_code:
                    type: integer
        '400':
          description: Solicitud incorrecta, falta alguna imagen o hay un error en los datos proporcionados.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
                  status_code:
                    type: integer
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
                  status_code:
                    type: integer

  /api/check-duplicate:
    post:
      summary: Verificar duplicado de usuario
      description: Verifica si un usuario ya existe en la base de datos basado en email, matnum o username.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: Correo electrónico del usuario.
                matnum:
                  type: string
                  description: Número de matrícula del usuario.
                username:
                  type: string
                  description: Nombre de usuario.
              required:
                - email
                - matnum
                - username
      responses:
        '200':
          description: No se encontraron duplicados
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  status_code:
                    type: integer
        '400':
          description: Solicitud incorrecta, campos faltantes
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
                  status_code:
                    type: integer
        '409':
          description: Usuario ya registrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
                  status_code:
                    type: integer
                  duplicate_field:
                    type: string
                    description: Campo que causa la violación de unicidad (username, matnum o email).
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
                  status_code:
                    type: integer