openapi: 3.0.0
info:
  title: API de Verificación de Rostros y Usuarios
  description: API para la verificación de rostros, inicio de sesión y registro de usuarios.
  version: 1.0.1
servers:
  - url: http://localhost:5000
    description: Servidor local
  - url: https://living-improved-ocelot.ngrok-free.app/
    description: Servidor en linea

paths:
  /api/signup-user:
    post:
      summary: Registrar usuario
      description: Registra un nuevo usuario proporcionando los datos necesarios.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Nombre completo del usuario.
                username:
                  type: string
                  description: Nombre de usuario.
                age:
                  type: integer
                  description: Edad del usuario.
                faculty:
                  type: string
                  description: Facultad a la que pertenece el usuario.
                matnum:
                  type: string
                  description: Número de matrícula.
                password:
                  type: string
                  description: Contraseña del usuario.
                face_img:
                  type: string
                  format: base64
                  description: Imagen de rostro en base64.
                email:
                  type: string
                  format: email
                  description: Correo electrónico del usuario.
              required:
                - name
                - username
                - age
                - faculty
                - matnum
                - password
                - face_img
                - email
      responses:
        '201':
          description: Registro de usuario exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      message:
                        type: string
                  status_code:
                    type: integer
        '400':
          description: Faltan campos en la solicitud
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
                  status_code:
                    type: integer
        '409':
          description: Usuario ya registrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
                  status_code:
                    type: integer
                  duplicate_field:
                    type: string
                    description: Campo que causa la violación de unicidad (username, matnum o email).
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
                  status_code:
                    type: integer

  /api/login-user:
    post:
      summary: Iniciar sesión de usuario
      description: Permite a un usuario iniciar sesión proporcionando su número de matrícula y contraseña.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                matnum:
                  type: string
                  description: Número de matrícula del usuario.
                password:
                  type: string
                  description: Contraseña del usuario.
              required:
                - matnum
                - password
      responses:
        '200':
          description: Inicio de sesión exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      message:
                        type: string
                      face_img:
                        type: string
                        format: base64
                        description: Imagen de rostro en base64.
                  status_code:
                    type: integer
        '400':
          description: Solicitud incorrecta, campos faltantes
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
                  status_code:
                    type: integer
        '402':
          description: Usuario no encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
                  status_code:
                    type: integer
        '403':
          description: Contraseña incorrecta
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
                  status_code:
                    type: integer
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
                  status_code:
                    type: integer

  /api/verify-face:
    post:
      summary: Verificar coincidencia de rostros
      description: Compara dos imágenes de rostros y determina si coinciden.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cap_frame:
                  type: string
                  format: base64
                  description: Imagen capturada en formato base64.
                ref_frame:
                  type: string
                  format: base64
                  description: Imagen de referencia en formato base64.
              required:
                - cap_frame
                - ref_frame
      responses:
        '200':
          description: Coincidencia de rostros exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      match:
                        type: boolean
                  status_code:
                    type: integer
        '400':
          description: Solicitud incorrecta, falta alguna imagen o hay un error en los datos proporcionados.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
                  status_code:
                    type: integer
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error:
                    type: string
                  status_code:
                    type: integer